### ISSUE TITLE
Author listed as Unknown by calibre 3.45.2

### ISSUE THREAD

**Issue by clarkspark** [standardebooks/kate-chopin_short-fiction#1]
This is the only SE work I have recognized which when loaded into calibre does not have an author listed (is listed as Unknown).  It is the epub download that I am seeing this with.

Let me know if I can provide you with more information.

Thanks.

**Comment by acabal** [comment]
Hi there, sorry for the late reply. I'm not sure why that would be. Have you tried filing a bug against Calibre?

**Comment by clarkspark** [comment]
No problem on the delay.  I just used "exiftool kate-chopin_short-fiction.epub" (from the command line on linux) to look at the metadata of this epub.  The Creator property is returned as:
    "Kate Chopin, Unknown"

I thought that this epub was the only one of the ~150 Standard Ebooks (SE) I've downloaded to have this issue.  But it turns out it also exists in; Flatland, and Tractatus Logico Philosophicus.  Both of those epubs also have a similiar value for the Creator property.

There seems to be a correlation between the Creator property containing "..., Unknown" and the author being listed as "Unknown" by Calibre.  I may be able to modify how Calibre identifies the author name when it contains a comma, but it seems odd that those three epubs (at least) have an odd Creator value and so many others do not.

**Comment by acabal** [comment]
My version of exiftool returns creator: Kate Chopin.

What these all have in common is that the creator has multiple roles. In this case Kate Chopin is both the author and the annotator (since she wrote the endnotes). In Tractatus the author also wrote the preface, etc. So, if these programs are finding the first role and selecting it instead of the "author" role, then that's a bug in those programs.

**Comment by acabal** [comment]
You should check that you have the latest version of Calibre, as this bug rings a bell for me and I think it was fixed quite some time ago. Calibre is updated very often. You can also file a bug there and the maintainer is very responsive. But, this is not a problem with the ebooks.

**Comment by clarkspark** [comment]
I do keep my Calibre up to date (currently 3.45.2) , which means not using the Debian package.  This brings its own complications.  I was thinking that having a seperate tool (exiftool; currently 11.16 for me) come back with unknown in the creator property would show that it was not a Calibre issue.   It's odd (to me) that our exiftools return different values for that property.   Just out of curisoty what version of exiftool do you have?

**Comment by acabal** [comment]
10.80, the default in the Ubuntu 18.04 repos.
